version: '3.4'

x-service: &default-service
  build: .
  env_file:
    - .env
  volumes:
    - ./app:/var/www
    - profile:/var/profile

services:
  composer:
    << : *default-service
    command: composer install

  test:
    << : *default-service
    command: composer test

  api:
    << : *default-service
    cap_add:
      - SYS_PTRACE
    restart: always

  worker:
    << : *default-service
    cap_add:
      - SYS_PTRACE
    restart: always
    command: ["php", "-f", "public/worker.php"]

  nginx:
    build: ./nginx
    depends_on:
      - api
    ports:
      - 80:80

  redis:
    image: redis

volumes:
  profile:
    external: false