POST {{ api_url }}/schedules/file
accept: application/json
Authorization: Bearer {{ accessToken }}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="file"

< ./sch.xlsx
--WebAppBoundary--

###
